version: '{build}'

image:
- Visual Studio 2017
- Ubuntu1804

build:
  verbosity: minimal

clone_depth: 1

environment:
    matrix:
        - ARCH_BUILD: x86_64
          ARCH: x86_64
          PYTHON: "C:\\Python37-x64"
stack: python 3.7

matrix:
  fast_finish: true

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017

    install:
      - set PATH=%PYTHON%/Scripts;%PYTHON%;%PATH%
      - pip.exe install --upgrade conan conan-package-tools
      - pip.exe install --upgrade --pre sesame-package-tools
      - conan user
      - conan profile new --detect default

  -
    matrix:
      only:
        - image: Ubuntu1804

    install:
      - pip3 install --upgrade conan conan-package-tools
      - pip3 install --upgrade --pre sesame-package-tools
      - conan user
      - conan profile new --detect default

build_script:
  - sesame build --windows --upload --channel stable
