build: false

configuration:
  - Debug
  - Release

environment:
    PYTHON: "C:\\Python37-x64"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          ARCH_BUILD: x86_64
          ARCH: x86_64

matrix:
  fast_finish: true

install:
  - set PATH=%PYTHON%/Scripts;%PYTHON%;%PATH%
  - pip.exe install --upgrade conan
  - pip.exe install --upgrade sesame-package-tools conan-package-tools bincrafters-package-tools
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

test_script:
  - ps: sesame build --windows --upload
